parent=keycloak
import=common/keycloak

styles=css/login.css

locales=da,en

# Make the inherited template inject our banner via the page header area.
kcHeaderClass=aabenforms-header
kcLoginClass=aabenforms-login
kcFormHeaderClass=aabenforms-formheader
kcContentWrapperClass=aabenforms-content
kcFormClass=aabenforms-form
kcInputClass=aabenforms-input
kcButtonClass=aabenforms-button
kcButtonPrimaryClass=aabenforms-button-primary
kcButtonBlockClass=aabenforms-button-block
kcButtonLargeClass=aabenforms-button-large
