<?php

/**
 * @file
 * ÅbenForms Core module.
 *
 * Provides base services and utilities for the ÅbenForms platform.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function aabenforms_core_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.aabenforms_core':
      return '<p>' . t('Core services and utilities for the ÅbenForms platform.') . '</p>';
  }
}
